baseURL = "https://apartamentosturisticoslarrabide.es/"
languageCode = "es"
title = "Apartamentos Turísticos Larrabide"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
