baseURL = "https://apartamentosturisticoslarrabide.es/"
locale = "es-ES"
title = "Apartamentos Turísticos Larrabide"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
